### ISSUE TITLE
initial release tryout

### ISSUE THREAD

**Issue by wickedOne** [wickedOne/plugin.video.nos.rio2016#1]
@ariep dit heb ik snel in elkaar gebeukt: niks fancy's met plaatjes en andere meta toestanden, maar het doet wat het moet doen.
laat maar ff weten of ie het ook bij jou doet...

**Comment by ariep** [comment]
Dit werkt perfect, hartstikke bedankt! Het schakelen tussen de verschillende sporten gaat heel soepel.

**Comment by wickedOne** [comment]
top!
graag gedaan.

zit zelf ook even te browsen; soms stuitert ie even omdat de buffer niet helemaal lekker is, maar dat kan aan mijn internet verbinding liggen...

mocht ik komend weekend nog een verloren moment hebben zal ik kijken of ik eea kan verrijken met meta data gezien ik best wel interessante informatie terug krijg:

``` json
{
      "channel" : {
        "id" : 30,
        "stream" : "/live/npo/sportzomer/npo1/npo1 .isml/npo1.m3u8",
        "title" : "[SPORTZOMER] NPO 1"
      },
      "description" : "Met live judo (Anicka van Emden strijdt rond 22.00 uur om brons), teamfinale (v) turnen met Nederland  en boksen -60 kg (Enrico Lacruz, achtste finale).",
      "discipline" : {
        "abbr" : "QL"
      },
      "end_at" : "2016-08-09T23 :15:00+0200",
      "has_dutch_participants" : true,
      "is_live" : false,
      "is_medal_event" : false,
      "livestream_id" : 2124322,
      "start_at" : "2016-08-09T22:00:00+0200",
      "stream_icon" : {
        "copyright" : "IOC",
        "formats" : {
          "height" : 150,
          "url" : {
            "png" : "http://s.nos.nl/img/os2016/icons/rio-live .png"
          },
          "width" : 150
        }
      },
      "title" : "Rio Live",
      "type" : "livestream"
    }
```

nice to have voor dit moment...
